#!/bin/sh

if [[ $1 == "start" ]]; then
    echo "Running Tracking Service"
    cd "Tracking/bin/"
    export LD_LIBRARY_PATH=.
    ./libtrack_server &
    echo "Running TouchFree Service"
    cd "../../TouchFree/"
    export LD_LIBRARY_PATH=.
    ./TouchFree_Service &
elif [[ $1 == "stop" ]]; then
    killall libtrack_server
    killall TouchFree_Service
fi